### ISSUE TITLE
Map file format

### ISSUE THREAD

**Issue by tgjones** [TheAssemblyArmada/Thyme#1]
Nice project name :) It took me a few minutes to get it...

I'm vaguely contemplating embarking on a similar project to Thyme, although with some different goals. I was wondering, do you have any information regarding the `.map` format as used by Generals and Zero Hour? The `.w3d` format seems quite well understood, but I haven't found any information about the binary format of `.map` files. This may well be because there isn't any.

**Comment by OmniBlade** [comment]
I don't think there is any as of yet (certainly none that I could find) and I haven't reached the map loading code yet to start producing my own documentation on the format (still working my way though classes involved in the engine initialisation). I believe it uses a similar chunk format to .w3d, at least in places, but that is about as much as I know so far.
Drop by our IRC channel for a chat at some point or clone the repo and get my e-mail address from the commit logs if you want to discuss in more details what we currently do and don't know.
