### ISSUE TITLE
Maps with custom scripts show no starting positions and player spawns as observer

### ISSUE THREAD

**Issue by xezon** [TheAssemblyArmada/Thyme#1053]
Maps with rising water feature show no starting positions. Is Thyme specific bug.

Map:
[Dammed Cottages ZH v1.zip](https://github.com/TheAssemblyArmada/Thyme/files/13955933/Dammed.Cottages.ZH.v1.zip)

![shot_20240116_222224_1](https://github.com/TheAssemblyArmada/Thyme/assets/4720891/897a4a3a-ec11-4ba8-8739-b278c4bffc13)

**Comment by xezon** [comment]
Also happens with other maps that have no rising water. I suspect the common denominator here is rather that these maps have player scripts.

As a result the player also does not spawn as a faction in the world and cannot control the units. Player spawns as Observer instead.

![shot_20240210_215743_2](https://github.com/TheAssemblyArmada/Thyme/assets/4720891/6278cbcd-f948-40fc-9efc-383c3f94c78f)

**Comment by 6emmes** [comment]
Rename to "Thyme fails to parse player staring positions when regenerating cache". The issue is much wider and is affecting any new map in Thyme map folder not parsed by vanillaZH beforehand.
