### ISSUE TITLE
Building Animation Display Bugs

### ISSUE THREAD

**Issue by duncanspumpkin** [TheAssemblyArmada/Thyme#176]
#### Original game source: game disc (I think)

- Reproducible in the original Generals Zero Hour? No
- Multiplayer affected? Not tested
- Are you using any mods? No

### Issue explanation
Building animations for the particle cannon are not working. They seem to be on a constant loop of opening up the cannon then closing again. I've only noticed it on the particle cannon but it's probably affects all building animations like that.

### Steps to reproduce the problem
1. Build particle cannon (I used the super weapons general but it shouldn't matter)
2. Observe animation.

**Comment by tomsons26** [comment]
Can't seem to reproduce
did you load a save that had the building building or being placed? this is a known bug in ZH when you do that

**Comment by duncanspumpkin** [comment]
Yeah sorry it mysteriously fixed itself at some point in the past month. I was going to bisect and find out what caused it but never got round to it
