### ISSUE TITLE
"Logs show Please call delete Instance instead of delete."

### ISSUE THREAD

**Issue by Coldfusionstorm** [TheAssemblyArmada/Thyme#232]
#### Original game source: Origin the Complete Collection.

- Reproducible in the original Generals Zero Hour? No.
- Not a Multiplayer game
- Not using any mods

### Issue explanation
The game simply lags to the point it becomes unplayable.

The issue can be seen in the attached log files the game keeps writing out this log:
"DEBUG C:\Users\Fredericik\Desktop\ThymeZH\Thyme\src\game\common\system\datachunk.h:40: Please call deleteInstance instead of delete."

### Steps to reproduce the problem
1.install latest release 24-03-2021 Debug Win32 on win10.
2.Start game
3.Play with any amount of AI game will lag
[ThymeDebugLogPrev.txt](https://github.com/TheAssemblyArmada/Thyme/files/6199808/ThymeDebugLogPrev.txt)

### Log files
Attached files.
[ThymeDebugLogPrev.txt](https://github.com/TheAssemblyArmada/Thyme/files/6199811/ThymeDebugLogPrev.txt)

### Screenshot(s) or video
i do have a long video recording ask if needed i would have to compress it down or scale to size or something.

EDIT: On further investigation it seems to be when units die/gets destroyed specifically.

**Comment by tomsons26** [comment]
Logging isn't a issue, there are multiple issues here

**Comment by Coldfusionstorm** [comment]
> Logging isn't a issue, there are multiple issues here

Yeah, The title fits poorly now, While it's true that it did have chunk collection that's not the "real" performance issue i was having.

**Comment by Coldfusionstorm** [comment]
Reopened.
