### ISSUE TITLE
Game Freezes for a second when a unit dies. (infantry excluded).

### ISSUE THREAD

**Issue by Coldfusionstorm** [TheAssemblyArmada/Thyme#236]
Operating System: Windows 10
Commit/build: [e.g. 30376e1]
Original game source: Origin the Complete Collection.

### Issue explanation
When units die the game freezes for a second this excludes infantry.
Sometimes this does not happen for units i expect it's depending on which explosion is being used.

### Steps to reproduce the problem
1.install latest build as of date 26-03-2021 - 937b4ec
2.Lose a unit or building that isn't infantry.

### Log files
[ThymeDebugLogFile.txt](https://github.com/TheAssemblyArmada/Thyme/files/6213639/ThymeDebugLogFile.txt)

**Comment by tomsons26** [comment]
Funnily enough wasn't a issue on 7, getting this now on Win 10.... Will try to debug at some point
