### ISSUE TITLE
Add support for the Origin The Ultimate Collection (TUC)

### ISSUE THREAD

**Issue by mrtnptrs** [TheAssemblyArmada/Thyme#25]
At the moment you need to copy 'game.dat' from your original Generals Zero Hour CD-rom installation to your TUC-installation folder. If it is possible for you to add support for TUC, this is why I think it would be a really good change:

1. This generally stimulates people to look at the internet for this 'game.dat' file by generally **illegally downloading** a kind of cracked version of this file. 
2. Original CD's are getting **old, scratched, thrown away accidentially and broken**.
3. Original installation/setup doesn't go quite as smooth on **new OS**:
-CD-drive makes sound like a **jet**. It's almost like the CD-drive is eating the CD-ROM. Tested on a laptop and multiple computers.
-Windows explorer often freezes or crashes when you try to open the CD-ROM content.
-There are more and more laptops and computers which **don't have a CD-rom drive anymore**.
-**SafeDisc** prevents you from using the vanilla version after installation on Windows 10 without Thyme or an illegal and potentially dangerous NO-CD-crack.
-Installation takes a huge lot of time (**4 CD-rom**s in my case, not even the patching included) and people are **lazy** XD
-Likely that the InstallShield won't work after a future update of Windows as it is getting quite old and has many error codes to throw at you :(
-Likely that the patches won't work anymore in a future version of Windows as they are getting older too.
-It is known that many people get errors in-game with the disc version that complains about the serial code of the game being invalid. Although, I'm not sure if this still occurs with the TUC version and if Bibber's fixed launchers fixed this.
4. CD-version of Generals Zero Hour is almost **not available anywhere to buy** anymore. This prevents people, who never played Zero Hour before, to try it by using Thyme.
5. More and more people **just don't use CD-roms anymore** and use only downloadable games from like Origin. Like the CD-roms laying somewhere catching dust.....

So, would this be possible? I think it would generally stimulate more people to use Thyme, as it will be less of a hassle.  Edit: see @OmniBlade reaction below for the answer to this question.

**Comment by mrtnptrs** [comment]
According to what @tomson26 said: "with Origin the complication is EA recompiled those binaries with a new version of Visual Studio,  2007(iirc) which means the code in the binary will be up to drastically different, which means we can't just do a binary difference of the databases to find the same functions quickly(as that uses checksuming of function blocks)" Does this mean Thyme can't be compatible without the original EXE in the game.dat file? (while in the origin version, this game.dat file seems to have been included in the launcher exe.)

**Comment by OmniBlade** [comment]
It should be noted that no one playing online actually uses the exe provided by Origin, they have to use Bibbers fixed launchers.

Unfortunately I didn't know that when I started this or I would have based thyme against the game.dat Bibber ships instead as its more widespread. I would have to spend a lot of time reapplying the mapping I've done of the 1.04 dat over to the one Bibber ships and spend yet more time updating all the addresses in Thyme to point to the new addresses.

Given that I don't want to ship the game.dat with Thyme myself to give EA as little reason as possible to C&D the project I'm in a bit of a difficult situation. I've posted links to a copy of the game.dat elsewhere, but would rather not link to it directly from this project.

**Comment by mrtnptrs** [comment]
I also indeed use Bibbers fixed launchers. Sadly, his site has been down for a few weeks already, saying "maintenance." And you will also have the chance of course that he will update his launcher in the future and thus changing the game.dat again..... or maybe that he will eventually not update it anymore. Then an Origin update could render it not-working again :(

**Comment by Hoeze** [comment]
I do not use any CD drive any more, only in my server is an old drive left.
Years ago I created images of all my CD's and stored them on a RAID 1.

This way I can mount the CD images directly without having to use any CD drive.
Also, I cannot loose any data due to CD ageing.

**Comment by mrtnptrs** [comment]
@Hoeze I assume you don't use Windows 10? Otherwise it will be a huge pain in the ass to install Windows 10. I tried to copy the CD-ROMs, but it seems almost impossible as I can't get it to run and the imaging process takes ages. So, how did you do that? Btw, I updated the first post I made in this issue with more reasons to support TUC, although I know it's pretty hard for OmniBlade to do this.

**Comment by Hoeze** [comment]
@mrtnptrs Yes, I am using Win10 since a month.
What's your exact problem? I simply used WinCDEmu to mount the image and installed it as always.
Next, I installed GenTool. Working like a charm.

**Comment by mrtnptrs** [comment]
@Hoeze And are you then also able to run it vanilla? (thus without Thyme?) As I get an annoying error then about it needing Administrator Privileges. As SafeDisc doesn't work anymore on Windows 10, doesn't this prevent Generals vanilla from running on Windows 10 without a kind of emulation of SafeDisc? And doesn't SafeDisc also prevent you copying the CD-ROMs correctly? I managed to copy the CD-Roms by using Alcohol 120%, but I got that admin privileges error and it took hours to copy the CD-ROM's. I will take a look at WinCDEmu and see if that solves my problem.

Edit: maybe a guide could be written about this subject. But it would be of course better if we could ship the Game.dat file with Thyme (if only we then didn't have to fear EA taking this project down) and just advice people to buy the TUC version.

**Comment by Hoeze** [comment]
@mrtnptrs I did not install it into C:\Program Files. I'm installing all my games to a special "games" folder, so changing files does not need any Admin privileges.
I'm not sure if it runs in vanilla as well, since installing GenTools is the first thing I do when it comes to Generals.

I'm using the First Decade version, maybe this makes a difference?

**Comment by mrtnptrs** [comment]
I use the Deluxe Edition of Generals (Zero Hour). But do you mean that you can run Generals (Zero Hour) without Thyme? I could indeed also try to install it to a different location indeed, but it will very likely not fix the problem.

**Comment by Hoeze** [comment]
I'm not using Thyme atm, but GenTool.
I will try it without any patches next time I play generals, but I'm pretty sure it will run in vanilla mode too.

**Comment by mrtnptrs** [comment]
Haha, that would be really nice. Could it be that The First Decade version has no SafeDisc DRM? Oh, or did you patch TFD to 1.03, that makes no DVD-rom neccesary? And does Thyme work with the Game.dat from TFD?

**Comment by mrtnptrs** [comment]
Ok, even WinCDEmu seems to have problems with the disc: it correctly sees all the "bad" sectors (which can be ignored and are caused by SafeDisc), but it copies the disc reeeeeeeeeeeeeeeeeeally slow :( Hopefully it works. Doing this with Daemon Tools is a disaster: it almost completely freezes when it looks for the disc and always fails to copy it eventually :(

**Comment by mrtnptrs** [comment]
Regarding that "Please login with administrator privileges and try again" error: according to this thread on a Dutch website (https://gathering.tweakers.net/forum/list_message/44821700.) it is very likely that that error is just the SafeDisc DRM kicking in as it can't find the secdrv driver. And it seems like Daemon tools as well as Alcohol 52%/120% don't support SafeDisc emulation on Windows 10 as the needed secdrv driver got removed in Windows 10.

**Comment by Hoeze** [comment]
Maybe missing SafeDisk could be the solution why it works for me, idk.
I tested Generals in vanilla mode. It still recognizes the emulated image, i.e. it complains about it, when it's missing. However, I only get till the blue loading screen, then Generals stops working.

This means that GenTool is required for running Generals on Win10, but it does not touch any DRM things.

**Comment by Hoeze** [comment]
Ah, I got it running in vanilla by creating options.ini file in "Documents\Generals Zero Hour" (or something like that)

**Comment by OmniBlade** [comment]
Yes, there is an issue with correctly detecting the graphics hardware if you don't have valid LOD settings in your options.ini. It causes the game to try and run an internal benchmarking suite to determine what settings to use, but that can take 10-20 minutes to complete, making the game appear hung in the mean time. I'm not even sure it will successfully complete with the game version as is.

Regarding possible solutions to distributing the game.dat, a possible compromise would be to generate a binary patcher against the TFD and origin versions perhaps?

**Comment by mrtnptrs** [comment]
What do you mean exactly with a binairy patcher?

**Comment by OmniBlade** [comment]
A patch that converts a TFD or origin game.dat into a 1.04 game.dat.

**Comment by mrtnptrs** [comment]
Isn't that really hard, as you have to find out every little change they made in the code? This will also break your Origin installation itself as it can then only be played through Thyme. A solution would be to first copy the Origin executable and edit the copy of it. So, how do these kind of things work then? :) Would it be really that huge of a risk to ONLY provide the original executable that still has the copy protection as usual? The people would still need the original game for its assets.

**Comment by Hoeze** [comment]
How about simply bin-patching the origin game to the 1.04 version? I.e. apply the diff between origin and 1.04 to avoid copyright issues?

**Comment by mrtnptrs** [comment]
@Hoeze You mean just replace it? Well, that could maybe be a potential risk as it is strictly not allowed to ship the original executable, even through a kind of patch. But then a simple download of the executable would be easier. Really, what a hassle, even my mind is blown XD Poor @OmniBlade ;) Haha, but what does he think?

**Comment by Hoeze** [comment]
I thought that it would not be necessary to ship the full binaries, if we only replace parts of the origin binaries.
I.e. we only ship 99,9% of the binary :grin:

**Comment by OmniBlade** [comment]
I was thinking something like an xdelta3 patch, which is yes a bin-patcher as a workaround to not shipping the actual binaries around. Large chunks should still be the same if they are built with the same compilers and options. I was thinking the workflow would be make a copy of the game.dat in a folder with the patch and patching tools, run a script file to convert the game.dat, copy it back being sure to back up the original (though the origin version can fix itself anyhow). Or maybe just do a patch against bibbers launcher since everyone uses that anyhow.

**Comment by OmniBlade** [comment]
I believe this is resolved by  80a7807 though it does require some work on the user end.
