### ISSUE TITLE
[Suggestion/discussion] Block the DLL-injection of GenTool (d3d8.dll)

### ISSUE THREAD

**Issue by mrtnptrs** [TheAssemblyArmada/Thyme#27]
I don't know if this can be done, but would the Thyme launcher/executable or the thyme DLL file be able to block the injection of GenTool DLL file (drd8.dll)? As many users use GenTool, they likely have it added to their installation of Zero Hour. As the injected code of GenTool could interfere with the injected code of Thyme, wouldn't it be better to block the GenTool code injection to prevent future false bug reports? @OmniBlade Aside from everything else, would this be even possible?

**Comment by OmniBlade** [comment]
I'm not sure its possible. I'd have to look at the documentation for DLL load calls to the win32 api and see if it can take absolute paths to the dll provided it is always located in the same place across windows installations.

**Comment by xezon** [comment]
Hello. Author of Gentool. You most likely just need to hook ntdll LoadLibrary funtion and then redirect the path when d3d8.dll comes through.

Alternatively GenTool could disable all its interfering features if you provide an identifier, e.g. by start parameter. Or I provide you with one.

**Comment by OmniBlade** [comment]
I probably wouldn't have to hook the LoadLibrary function, I already know where it is called during init and can reimplement that function and pass whatever I want to it. I would need to make sure the path I pass is always valid though, are there any environment variables that point to where the system d3d8.dll is located?

Without knowing exactly what functions GenTool calls from the original binary and which ones it replaces, its hard to say exactly which features would need to be disabled and eventually Thyme aims to replace everything with its own implementations anyway. You would probably be better placed to say what might interfere as you can see the code for both projects. I would welcome contributions to integrate GenTool features directly into Thyme  if you were interested or even any insight you have from your own explorations of the game binary.

**Comment by xezon** [comment]
There is a windows function to get the system path. There you just append \\d3d8.dll and you are good to go.

Gentool would know what to disable. It actually already has such a mode where it does zero modifications. That is when a user launches it in any d3d8 app that is not supported.

It certainly sounds appealing to have everything in thyme, but there are problems: from what i see thyme is early stage (how much % is reversed?) with the last commit 11 months ago. Gentool is a working and polished product that went a long way and has high adoption. It makes little sense to reimplement major features with thyme. Gentool has a lot of ugly code that would not pass code review, thus need reimplementation. And gentool has some client side anti cheat features. In an open source environment you could deactivate anti cheat and recompile it.

Maybe you can, if not done already, provide a step by step guide how users can help reversing. I am pretty sure 99.99 % of players would not know where to start looking.

**Comment by mrtnptrs** [comment]
@xezon If you take a look at the development branch (instead of the Master branch), you see that OmniBlade has made many commits, the latest 26 dags ago. He also made a new pull request today. Not that I'm a developer, but wouldn't it be a GOOD idea to implement new functions/features from Gentool into Thyme and in the progress make the code less ugly to make it really polished. Also, Thyme could eventually make many changes to Generals, like even more graphics options, better AI, better pathfinding, fixing crashing bugs (like the alt-tab bug I reported) and fixing other bugs in Generals. So, I don't see why Thyme couldn't contribute to the quality of the game like OpenRCT2 for example did.

**Comment by xezon** [comment]
Gentool on its own has a lot of code, so the complexity of porting features is significant. For virtually no benefit in short and mid term, it is not worth the effort. I like the fact that thyme dives in deep and would allow to tweak code easier. But the anti cheat problem remains. With thyme you would have a hard time providing client side anti cheat. Its a key point of gentool.

**Comment by OmniBlade** [comment]
@xezon I don't expect Thyme to be a replacement for GenTool any time soon for the majority of users, particularly those playing the original unmodded games. I'd estimate maybe 1% of the engine is implemented currently but as @mrtnptrs states, the project is still very much active on the development branch and my staging fork https://github.com/OmniBlade/Thyme.

On the subject of anti-cheat, that is certainly a challenge in an open source environment to have purely client side as any client can just lie to the others, but even with gentool a determined attacker could reverse it and subvert the anti-cheat, its probably just beyond the skills of most would be generals cheaters.

I'll look into creating some kind of guide for would be contributors, at least into the specifics and conventions used in Thyme.

**Comment by xezon** [comment]
This issue has been fixed with GenTool 8.6. GenTool will now launch in reduced feature mode when Thyme is loaded.
