### ISSUE TITLE
Add support for buffered file write outs for File and Win32LocalFile

### ISSUE THREAD

**Issue by xezon** [TheAssemblyArmada/Thyme#304]
Every single file write issues a prompt write out to disk. Add an optional file write out mode that allows to hand over or allocate a write out buffer so that file writes are performed in chunks and not on each bytes written. Theoretically systems could implement their own write buffers when interacting with `File`, but it is more versatile and robust if `File` has support for such functionality natively.

This is a feature.

**Comment by duncanspumpkin** [comment]
Are you actually sure this is required? Modern os's buffer file writes even when you don't specify anything. You really need to go out of your way to force it to be un buffered.

**Comment by xezon** [comment]
You might be onto something:
https://docs.microsoft.com/en-us/windows/win32/fileio/file-buffering

> When opening or creating a file with the CreateFile function, the FILE_FLAG_NO_BUFFERING flag can be specified to disable system caching of data being read from or written to the file. Although this gives complete and direct control over data I/O buffering, in the case of files and similar devices there are data alignment requirements that must be considered.

On that note, there appears to be an issue with Replay file write outs in game for some users:
https://www.reddit.com/r/generals/comments/3zie68/fixed_the_lag_issue_in_cnc_generals_zh/

> I found a fix (non-mod) to the Generals zero hour lag issues when either playing for extended periods of time, or for any time period in LAN play. The lag issue stems from the Replay file constantly updating and increasing. after about 15 minutes, the file becomes too large for the system to effectively handle. this happens on all systems, even high-end ones. The fix is to remove all permissions except for read-only to the replays folder where this file is saved.

I have not observed this myself yet.
