### ISSUE TITLE
Radar minimap is messed up

### ISSUE THREAD

**Issue by tomsons26** [TheAssemblyArmada/Thyme#429]
![game dat_wrJJim5sb8](https://user-images.githubusercontent.com/1433426/147420254-7ba096a7-a282-4d79-b4b5-b04f42b0325c.png)
Map is Death Valley

**Comment by jonwil** [comment]
Removing the hook for WorldHeightMap::Get_Terrain_Color_At makes this bug go away. Can't figure out why though.
