### ISSUE TITLE
Saving games fails

### ISSUE THREAD

**Issue by tomsons26** [TheAssemblyArmada/Thyme#430]

**Comment by jonwil** [comment]
Not present in commit 1e121cb433b3eb1f62c5685ae3e8ed62cc99e631 (More wwvegas fixes. (#367)).
Present in commit a4e5d23eafd774ade5872901d1372b02c9992419 (Particle System Parse (#300))

**Comment by jonwil** [comment]
Present in commit afe6eda728c477ee9b4e5ec2880618702536c958 (PartitionManager (#369))

**Comment by jonwil** [comment]
Seems to be caused by afe6eda728c477ee9b4e5ec2880618702536c958 (PartitionManager (#369))

**Comment by jonwil** [comment]
Found and fixed some issues with some Call_Method invocations in PartitionManager and PartitionCell and now save games work properly again.
