### ISSUE TITLE
Surveillance image flash doesn't work

### ISSUE THREAD

**Issue by tomsons26** [TheAssemblyArmada/Thyme#432]
Start USA1
![game dat_7G5U2pYqAk](https://user-images.githubusercontent.com/1433426/147420389-585d8905-ac57-4a17-a0f6-91cf9c4413ec.png)
These dont "flash" in

**Comment by jonwil** [comment]
Not present in commit 1e121cb433b3eb1f62c5685ae3e8ed62cc99e631 (More wwvegas fixes. (#367)).
Present in commit a4e5d23eafd774ade5872901d1372b02c9992419 (Particle System Parse (#300))

**Comment by jonwil** [comment]
Not present in commit afe6eda728c477ee9b4e5ec2880618702536c958 (PartitionManager (#369))

**Comment by jonwil** [comment]
Not present in commit c87d02a6057df40b6466eeeebbdaf25bb376e427 (Add u_strlcat and u_strlcat_tpl functions)

**Comment by jonwil** [comment]
Present in commit 498455a783eb29de891a6de5b24a1ed8a05d4899 (RTS2DScene and RTS3DInterfaceScene)

**Comment by jonwil** [comment]
Looks like 498455a783eb29de891a6de5b24a1ed8a05d4899 is at fault here.

**Comment by jonwil** [comment]
Fixed some issues related to W3DStatusCircle and now this works properly.
