### ISSUE TITLE
Sentry Drones can't fire

### ISSUE THREAD

**Issue by tomsons26** [TheAssemblyArmada/Thyme#433]
Start USA1
![game dat_aq4XkZ70V9](https://user-images.githubusercontent.com/1433426/147420409-cef2b175-92c9-4a95-8c88-4bb9e8cd6beb.png)

**Comment by jonwil** [comment]
Not present in commit 1e121cb433b3eb1f62c5685ae3e8ed62cc99e631 (More wwvegas fixes. (#367)).
Present in commit a4e5d23eafd774ade5872901d1372b02c9992419 (Particle System Parse (#300))

**Comment by jonwil** [comment]
Not present in commit afe6eda728c477ee9b4e5ec2880618702536c958 (PartitionManager (#369))

**Comment by jonwil** [comment]
Present in commit c87d02a6057df40b6466eeeebbdaf25bb376e427 (Add u_strlcat and u_strlcat_tpl functions)

**Comment by jonwil** [comment]
Present in commit cc74132671552a6b688de4e16a34e5bb1f78ca74 (Fixes visual regressions in water and bridge code. (#385))

**Comment by jonwil** [comment]
Present in commit e48cb623e085a4e8ea263788ee9e4057e6e96055 (TerrainTracksRenderObjClass and TerrainTracksRenderObjClassSystem (#383))

**Comment by jonwil** [comment]
Looks like a21a1e0a83a2cd46e9be7271c795e13171bac379 (Thing, ThingTemplate and ThingFactory (#370)) is the cause of this.

**Comment by jonwil** [comment]
It appears as though ThingFactory::New_Override or something it calls is the cause of this.

**Comment by jonwil** [comment]
Found the bugs and fixed them, this works now.
