### ISSUE TITLE
Some foliage renders black

### ISSUE THREAD

**Issue by xezon** [TheAssemblyArmada/Thyme#513]
Load Official Map in Skirmish: **Seaside Mutiny (2)**

![shot_20220117_222138_2](https://user-images.githubusercontent.com/4720891/149838541-65daf7b4-02d7-4972-9568-a96ad41ed348.jpg)

**Comment by jonwil** [comment]
Currently running a git bisect to try and track down this issue. Confirmed to be broken in commit 17fd60935f3af458cd8dea7c38d057fecb1978f6

**Comment by jonwil** [comment]
Confirmed to be broken in commit 314076c51062cd0f53cb62d9a8aefd1fde510934

**Comment by jonwil** [comment]
Confirmed to be broken in commit 96a13753042e0b40c32da768534d716254074ef3

**Comment by jonwil** [comment]
Confirmed to be broken in commit 5317fbb87e61205cd7098c2a1c1bc6b2fddbb620

**Comment by jonwil** [comment]
Confirmed to be broken in commit 565e660ae22a76c4787a6fcc38fe43af496dd617

**Comment by jonwil** [comment]
Confirmed to be broken in commit 2b8d40c86c7050c43572d4f3e5bce7f301093687

**Comment by jonwil** [comment]
Confirmed to be broken in commit 937b4ec87319fedb6613308a08e1fc3b8da81e5d
Unable to go any further back since I can't get builds before this one to compile.

**Comment by xezon** [comment]
If we cannot go back in history, next best thing is commenting out hooks.

**Comment by jonwil** [comment]
Managed to find a way to regression test further back. Commit b84fb6efa844bb47905777ed9c8819b569345540 is not broken.

**Comment by jonwil** [comment]
Confirmed not to be broken in commit cc692ddbdb2470448cda15daa722639838674c9a

**Comment by jonwil** [comment]
Confirmed to be broken in commit 4a192537783a55ba4657c0c0f74b9d8cc526b962 and not to be broken it commit 9a412ba28ccebad4ce173242506bbb87566d4831

**Comment by jonwil** [comment]
Confirmed not to be broken in commit ed724dc5c5d68b63364c78758ded0d6ae0969869

**Comment by jonwil** [comment]
Confirmed not to be broken in commit 3f5a118edabb972e3fa670f3566f7d80ad7ca973

**Comment by jonwil** [comment]
Confirmed not to be broken in commit 0212e9199b49426459be065796af3dfc1e66e65c

**Comment by jonwil** [comment]
Commit 4a192537783a55ba4657c0c0f74b9d8cc526b962 (Implement dx8renderer and dx8polygonrenderer) appears to be what broke this.
Going to investigate further.

**Comment by jonwil** [comment]
Problem seems to be in DX8RigidFVFCategoryContainer::Add_Mesh or something it calls. Can't be SortingVertexBufferClass::SortingVertexBufferClass, DX8VertexBufferClass::DX8VertexBufferClass, VertexBufferClass::AppendLockClass::AppendLockClass, FVFInfoClass::FVFInfoClass, DX8FVFCategoryContainer::Generate_Texture_Categories or VertexBufferClass::AppendLockClass::~AppendLockClass as those are hooked in the build I am testing.
