### ISSUE TITLE
Structure scaffolding does not show correctly

### ISSUE THREAD

**Issue by xezon** [TheAssemblyArmada/Thyme#528]
Structure scaffolding does not show correctly. On develop branch. Must have been introduced recently (before 31 Jan 2022).

![shot_20220131_212829_2](https://user-images.githubusercontent.com/4720891/151868572-de179f13-3b33-4a4f-b7a1-065357933a48.jpg)

**Comment by jonwil** [comment]
W3DModelDraw::Adjust_Animation is at fault here.

**Comment by jonwil** [comment]
Fix found in Test_Animation_Flag.
