### ISSUE TITLE
Duplicate weapon effects spawn at the center of the unit as well as on the weapon

### ISSUE THREAD

**Issue by xezon** [TheAssemblyArmada/Thyme#534]
Duplicate weapon effects spawn at the center of the unit as well as on the weapon. Can be tested with any unit that spawns muzzle flashes and particle effects when firing.

![shot_20220131_223300_5](https://user-images.githubusercontent.com/4720891/151877201-eab311c7-fb73-4bcd-ad3a-12794c8aa818.jpg)

**Comment by jonwil** [comment]
Seems to be caused (for the USA ranger at least) by W3DModelDraw::Handle_Weapon_Fire_FX

**Comment by jonwil** [comment]
Found a fix in W3DModelDraw::Handle_Weapon_Fire_Fx that solves this.
