### ISSUE TITLE
Hero unit has no build count cap

### ISSUE THREAD

**Issue by xezon** [TheAssemblyArmada/Thyme#544]
Hero unit has no build count cap. Originally only 1 Hero unit can be build.

Repro:
- Build USA Power, Supply, Warfactory, Barracks, Strategy Center
- Build multiple Colonel Burton in Barracks

![shot_20220205_010319_1](https://user-images.githubusercontent.com/4720891/152619779-df17e916-2863-4f43-9f16-5e69a66476a0.jpg)

**Comment by tomsons26** [comment]
doesn't happen if W3DThingFactory::Hook_Ctor hook is commented out
