### ISSUE TITLE
Hovering cursor over Civilian structures will not show rectangled cursor

### ISSUE THREAD

**Issue by xezon** [TheAssemblyArmada/Thyme#545]
Hovering cursor over Civilian structures will not show rectangled cursor. Instead the default arrow cursor shows.

I am unable to capture screenshot with the actual cursor.

![shot_20220205_113412_5](https://user-images.githubusercontent.com/4720891/152658189-c3bc6691-e89f-4004-8c38-a179d957addb.jpg)

**Comment by jonwil** [comment]
Have ruled out the mouse code.

**Comment by jonwil** [comment]
Currently running a git bisect to try and track down this issue. Confirmed to be broken in commit 17fd60935f3af458cd8dea7c38d057fecb1978f6

**Comment by jonwil** [comment]
Confirmed to be broken in commit 314076c51062cd0f53cb62d9a8aefd1fde510934

**Comment by jonwil** [comment]
Confirmed to be broken in commit 96a13753042e0b40c32da768534d716254074ef3

**Comment by jonwil** [comment]
Confirmed to be broken in commit 5317fbb87e61205cd7098c2a1c1bc6b2fddbb620

**Comment by jonwil** [comment]
Confirmed to be broken in commit 565e660ae22a76c4787a6fcc38fe43af496dd617

**Comment by jonwil** [comment]
Confirmed to be broken in commit 2b8d40c86c7050c43572d4f3e5bce7f301093687

**Comment by jonwil** [comment]
Confirmed to be broken in commit 937b4ec87319fedb6613308a08e1fc3b8da81e5d
Unable to go any further back since I can't get builds before this one to compile.

**Comment by jonwil** [comment]
Managed to find a way to regression test further back. Commit b84fb6efa844bb47905777ed9c8819b569345540 is broken.

**Comment by jonwil** [comment]
Confirmed to be broken in commit 80f180dbd87797e4a6ef495f9cb0993606f0efaf

**Comment by jonwil** [comment]
Confirmed to be broken in commit ef33d9f58695575af5d45664fe9a6f79e7d3501d

**Comment by jonwil** [comment]
Confirmed to be broken in commit 5fab8f0726481e18fc985d92936b05eb50a64f84

**Comment by jonwil** [comment]
Confirmed to be broken in commit 0794c3ab715a9c95412f815b65a7e756b32194b1

**Comment by jonwil** [comment]
Still seems to be broken in commit 162d0198432a02bdc72eb9cf8cf3551668779621 which is as far back as I can easily regression test.
