### ISSUE TITLE
USA Rangers have broken animation loop after landing from Paradrop

### ISSUE THREAD

**Issue by xezon** [TheAssemblyArmada/Thyme#554]
USA Rangers have broken animation loop after landing from Paradrop. Thyme bug.

You can use the attached test map to test promotions.

[!TestRank.zip](https://github.com/TheAssemblyArmada/Thyme/files/8044141/TestRank.zip)

![shot_20220210_213923_1](https://user-images.githubusercontent.com/4720891/153493064-05fe9942-af1c-4974-a044-f906bc8fa986.jpg)

![shot_20220210_213942_2](https://user-images.githubusercontent.com/4720891/153493069-ffbfee9f-43ef-4fcd-aa81-7df44ab1b154.jpg)

**Comment by jonwil** [comment]
Currently running a git bisect to try and track down this issue. Confirmed not to be broken in commit 17fd60935f3af458cd8dea7c38d057fecb1978f6 and to be broken in commit 47918425eabb6e61c2719ecba454309bac06b8df

**Comment by jonwil** [comment]
Confirmed to be not broken in commit f95ea5c66e3ecd31930f36883764f14d8d287cff

**Comment by jonwil** [comment]
Confirmed to be broken in commit d456bb599645c17d2b274af422aed64beb1980ee

**Comment by jonwil** [comment]
Confirmed not to be broken in commit 8dbcca33a94c3500859b22974d910af5fc450428

**Comment by jonwil** [comment]
Confirmed to be broken in commit a4ce71d6d0a75b06b2ebb249454056bb668525f6

**Comment by jonwil** [comment]
Confirmed not to be broken in commit 923b36344280fba92af920f379054db5346a9327

**Comment by jonwil** [comment]
Commit a4ce71d6d0a75b06b2ebb249454056bb668525f6 (Implement ModelConditionInfo and W3DModelDrawModuleData) seems to be what broke it.

**Comment by jonwil** [comment]
Have narrowed it down to W3DModelDrawModuleData::Parse_Condition_State (or something it calls/references)
