### ISSUE TITLE
Planes have wrong rotation on airfield when standing, starting and landing

### ISSUE THREAD

**Issue by xezon** [TheAssemblyArmada/Thyme#561]
Introduced with https://github.com/TheAssemblyArmada/Thyme/commit/7f1203a55da1ad8fe00d11cb6108aa4bf6f873de

![shot_20220212_234310_1](https://user-images.githubusercontent.com/4720891/153731153-74fbaf90-5ec3-474a-8ae2-f34afe52141d.jpg)

**Comment by tomsons26** [comment]
They are fine when W3DThingFactory::Hook_Ctor isn't hooked

**Comment by xezon** [comment]
Can't reproduce this anymore as of right now

**Comment by xezon** [comment]
Issue is reproducible with latest code.

Just build some Raptors on USA Airfield.

![shot_20221002_131024_2](https://user-images.githubusercontent.com/4720891/193451026-718298e7-923a-4b43-826b-2626ff9460d0.jpg)

**Comment by tomsons26** [comment]
something from the drawable.cpp hooks causes this

**Comment by xezon** [comment]
Check if happens in Release.

**Comment by xezon** [comment]
Issue does not happen in RelWithDebInfo configuration.

![shot_20221016_005322_1](https://user-images.githubusercontent.com/4720891/196010521-1f758623-55f7-42b4-ae64-a7c31ee6012a.jpg)
