### ISSUE TITLE
Weapon particles do not originate from weapon barrel

### ISSUE THREAD

**Issue by xezon** [TheAssemblyArmada/Thyme#574]
Weapon particles do not originate from weapon barrel. Seen on GLA Toxin Tractor. Not seen on any other unit yet.

There likely is a rotation missing to calculate world position with local rotation.

![shot_20220216_195210_1](https://user-images.githubusercontent.com/4720891/154336763-add0a071-e2ed-4bc8-a1b2-d8850d5b7232.jpg)

**Comment by jonwil** [comment]
Unable to reproduce this with current Thyme build. Calling it fixed at this point.
