### ISSUE TITLE
Binary Data Stream effect is missing texture

### ISSUE THREAD

**Issue by xezon** [TheAssemblyArmada/Thyme#607]
Binary Data Stream effect is missing texture. Can be reproduced with China Lotus disabling cars.

![shot_20220218_215414_5](https://user-images.githubusercontent.com/4720891/154816031-c1188390-2d8d-46e7-ab0d-1a525a4009e9.jpg)

**Comment by tomsons26** [comment]
Not seeing a pure green line, not seeing anything, SegLineRendererClass::Render seems to be what broke it

**Comment by jonwil** [comment]
If I change W3DModuleFactory::Init and replace W3DLaserDraw::Friend_New_Module_Instance and W3DLaserDraw::Friend_New_Module_Data with the game exe addresses, the issue goes away and the texture draws properly. If I make SegLineRendererClass::Render into Call_Method, the issue doesn't go away and the solid green line is still there.

**Comment by jonwil** [comment]
Making W3DLaserDraw::Do_Draw_Module into Call_Method doesn't make the issue go away either.
