### ISSUE TITLE
Helix Helicopter in Shellmap looks static without animations

### ISSUE THREAD

**Issue by xezon** [TheAssemblyArmada/Thyme#631]
Helix Helicopter in Shellmap looks static without animations.

![shot_20220226_193102_2](https://user-images.githubusercontent.com/4720891/155854990-d269b696-f599-4bd8-a7e8-6e8ab6995217.jpg)

**Comment by tomsons26** [comment]
The helix is in Held status true which grounds it, can be reproduced on a blank map when setting this
