### ISSUE TITLE
Thyme patched exe files are broken

### ISSUE THREAD

**Issue by jonwil** [TheAssemblyArmada/Thyme#692]
The Thyme patched exe files are set up to link to functions ?StartHooking@@YAXXZ and ?StopHooking@@YAXXZ (aka void StartHooking(); and void StopHooking(); but commit c9d3ddf1b605e00ffcb073d13c639dbb6e2c8b85 changed the exported functions to ?StartHooking@@YA_NXZ and ?StopHooking@@YA_NXZ aka bool StartHooking(); and bool StopHooking(); so when you try to start the patched exe, Windows says "can't find ?StartHooking@@YAXXZ" and the game doesn't start.

**Comment by xezon** [comment]
This is fixed right?

**Comment by duncanspumpkin** [comment]
Yes
