### ISSUE TITLE
Textured planes have wrong depth sorting

### ISSUE THREAD

**Issue by tomsons26** [TheAssemblyArmada/Thyme#711]
### Issue explanation

Viewed in the WIP W3D viewer but since it uses game code to draw everything issue is likely in game code.

### Screenshot(s) or video

![image](https://user-images.githubusercontent.com/1433426/162184750-aca9ed66-6c21-4f00-892a-1bea0b7540ce.png)

**Comment by tomsons26** [comment]
![image](https://user-images.githubusercontent.com/1433426/162189789-9031312d-b728-46cc-a9b2-8ed12e97358d.png)

**Comment by jonwil** [comment]
![heli](https://user-images.githubusercontent.com/4471249/191872132-28774f3c-bdd9-46ff-8582-b3521a6f9ef2.png)
This is what I get with the current w3dviewer for the Chinook. No more glitched rotor blades so I think we can call this fixed.
