### ISSUE TITLE
Corrupted model

### ISSUE THREAD

**Issue by tomsons26** [TheAssemblyArmada/Thyme#716]
### Issue explanation

PMStpLit02.W3D is corrupt when viewed with our code.
Viewed in the WIP W3D viewer but since it uses game code to draw everything issue is likely in game code.

### Screenshot(s) or video

looks like this
![w3dview_spZu2Dw0JX](https://user-images.githubusercontent.com/1433426/163710584-d65d5175-c359-40a1-a62c-d5c1ff849fc3.png)
should look like 
![W3DView_31ZuezziQr](https://user-images.githubusercontent.com/1433426/163710603-cf18f320-4b19-4c88-b911-2e1614570c68.png)

**Comment by jonwil** [comment]
![stop](https://user-images.githubusercontent.com/4471249/191863109-2a7f065c-5aec-4ca3-a28c-50d54098cc2b.png)
This is what PMStpLit02.W3D looks like in the completed w3dviewer. So whatever bug caused the previous problems seems to be sorted. I think we can close this issue now.
