### ISSUE TITLE
Chinook is pushed out of world after dropping Rangers

### ISSUE THREAD

**Issue by xezon** [TheAssemblyArmada/Thyme#767]
Chinook is pushed out of world after dropping Rangers. Tested in Debug configuration.

https://user-images.githubusercontent.com/4720891/196058477-8516e994-2a9b-4cae-8919-8522a5d5545a.mp4

**Comment by jonwil** [comment]
Occurs in commit 02750535193b8bab9e243d2f369a2711e5679fd9

**Comment by jonwil** [comment]
Occurs in commit d86155553b2a3a3ee3ac96a3ea886fa03b7cfeca

**Comment by jonwil** [comment]
Does not occur in commit 38676f8204b59714c0a71c071f7b62530ca605d8

**Comment by jonwil** [comment]
Does not occur in commit 2d54159bf5ceca7873db595b43c81aeed9c122e2

**Comment by jonwil** [comment]
Does not occur in commit 13a801b6bb3bd584a449a422a2651c63b3878552

**Comment by jonwil** [comment]
Occurs in commit ee68220c6303951b39a759aac0dad5b14e22fd06

**Comment by jonwil** [comment]
Does not occur in commit 3f949ac215835860781c3eb5dc46fed6087b0ace

**Comment by jonwil** [comment]
Narrowed it down to commit b7ee412400053c9c11da5ba3046f2a3ef9558616

**Comment by jonwil** [comment]
If the PhysicsBehavior::Friend_New_Module_Instance hook is enabled, issue happens.

**Comment by jonwil** [comment]
Fix for this added.
