### ISSUE TITLE
Track current progress in readme.

### ISSUE THREAD

**Issue by AnthonyJacob** [TheAssemblyArmada/Thyme#8]
Could you please add a task list to readme, with short description of current state of project (updated each month).

Example:

- [x] **Initialization** *100%*
   - [x] You can choose .big folder trough `-big /path/to/folder` flag
- [ ] **Multiplayer** *60%*
- [ ] **Scripts** *20%*
- [ ] **AI**
- [ ] **Graphics**
- [ ] **Engine**
   - [ ] Log crashes
   - [ ] Unlimited number of generals and upgrades.
- [ ] **etc**

**Comment by AnthonyJacob** [comment]
By the way if you would need a help with anything, that requires only very basic knowledge of assembly, basic knowledge of c or intermediate knowledge of scala / haskell I would be glad to help.

**Comment by OmniBlade** [comment]
I'm not sure its really suitable for the readme, but I will look at putting some projects and milestones together to give an idea of where we are at and what needs working on.

**Comment by Hoeze** [comment]
Is there already something like a progress report?

**Comment by OmniBlade** [comment]
I've created a [Progress Tracker](https://github.com/TheAssemblyArmada/Thyme/wiki/Progress-Tracker) on our wiki which give some insight into how we are doing. It includes a rought percentage of how much of the game has been reimplemented as well as descriptions of significant functional areas that are either completely or substantially reimplemented.

I would have liked to have put the table up of the functions we know about and their status, but it seems it would be too large for github to display.
