### ISSUE TITLE
Rocket Buggy vehicles are missing in Shell Map

### ISSUE THREAD

**Issue by xezon** [TheAssemblyArmada/Thyme#806]
Rocket Buggy vehicles are missing in Shell Map.

## Original

https://user-images.githubusercontent.com/4720891/205486033-4c4c6e4a-3baf-45b3-ae7c-160577e28fe1.mp4

## Thyme

https://user-images.githubusercontent.com/4720891/205486055-3e8aeeb7-4065-4e27-a72b-30b58b3df454.mp4

**Comment by xezon** [comment]
In latest Thyme I am able to observe that after a 4 loops into Shell Map more things become missing.

Eventually no more GLA Technicals, Rocket Buggys spawn on that path way.

![shot_20230122_111757_2](https://user-images.githubusercontent.com/4720891/213911338-2dce0e08-bbdc-4240-abd6-9d63a2d6f69e.jpg)

And eventually, the USA Ranger drop also drops USA Missile Defenders, which is unexpected. Or it turns missing entirely, like the GLA units.

![shot_20230122_111813_3](https://user-images.githubusercontent.com/4720891/213911363-b2a7da6f-6548-4e53-aba1-3b9387aefdbc.jpg)

**Comment by jonwil** [comment]
Occurs in commit 02750535193b8bab9e243d2f369a2711e5679fd9

**Comment by jonwil** [comment]
Occurs in commit d86155553b2a3a3ee3ac96a3ea886fa03b7cfeca

**Comment by jonwil** [comment]
Does not occur in commit 38676f8204b59714c0a71c071f7b62530ca605d8

**Comment by jonwil** [comment]
Does not occur in commit 2d54159bf5ceca7873db595b43c81aeed9c122e2

**Comment by jonwil** [comment]
Does not occur in commit 13a801b6bb3bd584a449a422a2651c63b3878552

**Comment by jonwil** [comment]
Does not occur in commit ee68220c6303951b39a759aac0dad5b14e22fd06

**Comment by jonwil** [comment]
Does not occur in commit 03da45836bef1e87f91b8ea1263b6b9570d42d4b

**Comment by jonwil** [comment]
Found a fix for this that seems to work.
