### ISSUE TITLE
Props renderer glitches

### ISSUE THREAD

**Issue by xezon** [TheAssemblyArmada/Thyme#816]
Props renderer glitches.

https://user-images.githubusercontent.com/4720891/211112129-8bd4b7c4-29ee-4b1f-a771-30cf3b77eda3.mp4

**Comment by xezon** [comment]
- Load map "Tournament Desert (2)"
- Move to the center of the map where the houses are

Tested in Release configuration.

**Comment by jonwil** [comment]
Does not appear to occur in commit 02750535193b8bab9e243d2f369a2711e5679fd9

**Comment by jonwil** [comment]
W3DPropBuffer::Draw_Props is the cause of this.

**Comment by jonwil** [comment]
Found a fix.
