### ISSUE TITLE
EvaEvent does not work

### ISSUE THREAD

**Issue by xezon** [TheAssemblyArmada/Thyme#832]
EvaEvent's do not work.

Repro: Start a Network match against 1 AI. Open menu, hit Surrender. Listen.

Expected: "Unit Lost", "We have been defeated" sounds

Thyme: no sounds

## Original

https://user-images.githubusercontent.com/4720891/215263236-9ab77755-593c-43a2-9ea3-198681051b0b.mp4

**Comment by tomsons26** [comment]
can't repro

**Comment by xezon** [comment]
Issue no longer happens with latest code. Closing.
