### ISSUE TITLE
Trees do not render correctly

### ISSUE THREAD

**Issue by xezon** [TheAssemblyArmada/Thyme#863]
Trees do not render correctly. Polygons stretch through world. Moving camera over trees will reduce FPS from 400 to 40 on my machine.

Tested with RelWithDebInfo. On map Manic Aggression (4).

![shot_20230218_004045_4](https://user-images.githubusercontent.com/4720891/219817428-17360a8c-a4b3-49d0-abd6-af599f84f6e1.jpg)

![shot_20230218_004159_5](https://user-images.githubusercontent.com/4720891/219817434-7564b437-33f7-4c37-9e0d-bda030e03dfe.jpg)

**Comment by jonwil** [comment]
![image](https://user-images.githubusercontent.com/4471249/219885214-b5731ab8-00af-4a8f-9dee-37f9a7a1b3f9.png)
This is what I get with the latest code. Unable to reproduce the corrupt trees so I am unable to do anything about it.

**Comment by xezon** [comment]
Does not happen with abe84bb08014eaca79425ae4028072cdf9b4cb93

**Comment by xezon** [comment]
Happens with 550b77abfda332385db554a106d01b932488e73c

Performance degradation is reproducible. Rendering issue cannot be seen, because all trees do not draw.

**Comment by xezon** [comment]
Happens with 03364d2de72e552092632ba001fbeaa472ce2307

Performance degradation is reproducible. Rendering issue can be seen.

**Comment by xezon** [comment]
Performance degradation introduced with W3DTreeBuffer::Do_Lighting

Render issue introduced with W3DTreeBuffer::Update_Vertex_Buffer

**Comment by jonwil** [comment]
The fix for the render issue seems to be to change this in Update_Vertex_Buffer
```
                    if ((tree_type >= 0 && (m_trees[tree].push_aside_move_time != 0.0f)
                            || m_trees[tree].topple_state != TTree::TOPPLE_UPRIGHT)) {
```
to this
```
                    if (tree_type >= 0
                        && (m_trees[tree].push_aside_move_time != 0.0f
                            || m_trees[tree].topple_state != TTree::TOPPLE_UPRIGHT)) {
```

I have examined Do_Lighting very thoroughly and can't find anything at all that seems to be cloned wrong or could be causing performance issues. Only difference is that we use Make_Color instead of raw code but that shouldn't cause issues given that we use Make_Color all over the code.

**Comment by xezon** [comment]
Performance degradation can be avoided with

```c++
inline int Fast_To_Int_Truncate(float val)
{
//#ifdef BUILD_WITH_GAMEMATH
//    return gm_lrintf(gm_truncf(val));
//#else
    return lrintf(truncf(val)); // TODO reimplement based on fdlibm for cross platform reproducibility.
//#endif
}
```

**Comment by xezon** [comment]
For performance issue, we now have isolated issue report at #864

This report now only concerns rendering issue with trees.
