### ISSUE TITLE
Need to add fast math functions

### ISSUE THREAD

**Issue by jonwil** [TheAssemblyArmada/Thyme#864]
There are many places in our code where we call into slow deterministic gm_xxxx functions from GameMath but that don't need to be deterministic. We should add faster versions of Max, Min, Pow, Cos, Sin, Sqrt, Acos, Asin, Atan, Atan2, Tan, Ceil, Floor, Fast_To_Int_Floor, Fast_To_Int_Ceil, Fast_To_Int_Truncate, Fast_Float_Floor, Fast_Float_Ceil and Lrintf and use those in places where we are confident that the results are not going to be sent over the network or stored in any files (save games, replays, maps etc)

**Comment by xezon** [comment]
Issue has been first spotted through **W3DTreeBuffer::Do_Lighting** function.

* See #863

In this particular case, performance degradation can be avoided by commenting out call to `gm_lrintf` function.

```c++
inline int Fast_To_Int_Truncate(float val)
{
//#ifdef BUILD_WITH_GAMEMATH
//    return gm_lrintf(gm_truncf(val));
//#else
    return lrintf(truncf(val)); // TODO reimplement based on fdlibm for cross platform reproducibility.
//#endif
}
```

The main offenders are calls to
* feholdexcept
* fesetenv
* fetestexcept

![performance](https://user-images.githubusercontent.com/4720891/219945570-82d61e7b-0f50-4176-b69d-4f6120e637c6.png)

**Comment by xezon** [comment]
Compiling out USE_GAMEMATH currently causes compile error
```
D:\Projects\TheAssemblyArmada\Thyme_Jonwil\src\w3d\math\gamemath.h(72,9): error C3861: 'gm_isnanf': identifier not found
```
