### ISSUE TITLE
GLA Bomb Truck can no longer attack

### ISSUE THREAD

**Issue by xezon** [TheAssemblyArmada/Thyme#888]
GLA Bomb Truck can no longer attack. When disguised and parked close to enemy unit, the Truck will not even undisguise.

Happens with 3018c18860270f436edc42c5fe3336a98e0ed994

![shot_20230401_231645_1](https://user-images.githubusercontent.com/4720891/229314960-ac614522-904d-4f28-89d1-44c8dd817f56.jpg)

**Comment by abramann** [comment]
Terrorist is same.

**Comment by xezon** [comment]
I narrowed it to `WeaponTemplate::Fire_Weapon_Template`. Everything else for WeaponTemplate, WeaponStore and Weapon is unhooked.
