### ISSUE TITLE
AI doesn't capture tech structures

### ISSUE THREAD

**Issue by jonwil** [TheAssemblyArmada/Thyme#898]
AI troops no longer capture civilian structures. Tested on Heartland Shield (2)
![232614037-c7184570-808a-404a-a2e5-73b2783bcb9e](https://user-images.githubusercontent.com/4471249/232640686-ae607618-1bd6-4fe7-a76c-91aaaa67c985.jpg)
100% confirmed as happening in #896
Possibly related to #825 or #882

**Comment by xezon** [comment]
Either something wrong with AI, capturing mechanic, or acquiring upgrades.

**Comment by jonwil** [comment]
Can confirm that AI is definitely acquiring (and using) generals points stuff (like fuel-air-bomb and paratroops)

**Comment by xezon** [comment]
It is possible to see upgrades on Control Bar when selecting enemy infantry guy.
