### ISSUE TITLE
Unknown Crash in W3DVolumetricShadow::RenderDynamicMeshVolume

### ISSUE THREAD

**Issue by tomsons26** [TheAssemblyArmada/Thyme#95]
Function is at 007a43d0 in ZH 1.04, crash happens 007A44BA, making a issue to so to keep this in mind when this is reimplemented.

**Comment by OmniBlade** [comment]
As it stands this issue report doesn't contain enough information to properly investigate, if more information on how to cause the crash comes to light we can reopen and investigate then.
